---

- name: Create /home/ubuntu/bin
  file: path=/home/ubuntu/bin state=directory

- name: Download repo
  get_url:
    url: https://storage.googleapis.com/git-repo-downloads/repo
    dest: /home/ubuntu/bin/repo
    mode: u=rx,g=rx,o=rx
    checksum: sha256:e147f0392686c40cfd7d5e6f332c6ee74c4eab4d24e2694b3b0a0c037bf51dc5

- name: Create source directory
  file: path={{ source_dir }} state=directory

# The option --depth=1 ensures a shallow clone which takes less time to download. 
- name: Run repo init
  command: repo init --depth=1 -u https://android.googlesource.com/platform/manifest -b {{ source_tag }}
  args:
    path: "{{ source_dir }}"

# The option -c limits downloads to the current branch.
- name: Run repo sync
  command: repo sync -c -j4
  args:
    path: "{{ source_dir }}"